const facts = [
    "I love hiking and have traveled to five national parks.",
    "I am an avid reader and read around 20 books per year.",
    "I once baked a 3-tiered cake for a family gathering.",
    "I speak three languages fluently.",
    "I’m learning to play the guitar in my free time.",
    "I have a black belt in karate.",
    "I built my own computer from scratch.",
    "I’ve visited over 10 different countries.",
    "I can solve a Rubik's Cube in under a minute.",
    "I enjoy stargazing and can identify several constellations.",
    "I’ve run a full marathon and several half-marathons.",
    "I once adopted a stray puppy I found on a road trip.",
    "I have a collection of over 100 vinyl records.",
    "I designed and sewed my own costume for a cosplay event.",
    "I enjoy experimenting with 3D printing.",
    "I’ve performed in a local theater production.",
    "I’m a certified scuba diver and love exploring coral reefs.",
    "I brew my own kombucha at home.",
    "I’ve painted a mural on a wall in my house.",
    "I collect vintage postcards from different cities.",
    "I can juggle three objects pretty well.",
    "I once volunteered to teach English in a rural village.",
    "I write poetry and have published a few in online journals.",
    "I’m fascinated by mythology and folklore from around the world.",
    "I’ve built a treehouse with my siblings.",
    "I love cooking and specialize in making Thai dishes.",
    "I’m passionate about bird watching and keep a detailed log.",
    "I’ve taken a hot air balloon ride at sunrise.",
    "I taught myself calligraphy during quarantine.",
    "I have a knack for identifying airplane models just by looking at them.",
    "I once stayed awake for 24 hours to photograph a meteor shower.",
    "I’ve attended a live recording of a popular podcast.",
    "I’m an avid cyclist and have completed a 100-mile ride.",
    "I’m learning sign language to communicate better with my cousin.",
    "I’ve organized a charity event that raised thousands of dollars.",
    "I built a hydroponic garden on my balcony.",
    "I’ve been to a concert of my favorite band in another country.",
    "I love escape rooms and have solved over 20 of them.",
    "I’ve swum in bioluminescent waters at night.",
    "I own a telescope and host star parties for my friends.",
    "I’ve volunteered at an animal shelter for several years.",
    "I’m learning to dance salsa and bachata.",
    "I’ve camped in the wilderness with no technology for a week.",
    "I have a passion for urban sketching and keep a sketchbook.",
    "I collect coins from different countries.",
    "I’ve made a stop-motion animation with clay figurines.",
    "I’m a trivia enthusiast and participate in local quiz nights.",
    "I’ve planted a vegetable garden and harvest my own produce.",
    "I enjoy geocaching and have found over 200 hidden caches.",
    "I’ve recorded a song in a professional studio for fun."
    
];

function showFact() {
    const factIndex = Math.floor(Math.random() * facts.length);
    document.getElementById('factDisplay').innerText = facts[factIndex];
}
